### ISSUE TITLE
Plugin is very great, but error version 3.4.4 stable

### ISSUE THREAD

**Issue by CleberSGoncalves** [piccio/redmine_watchers_groups#1]
An error is occasioned when creating a new task and using the Watchers field from within the task. But if you create the activity and then add the Watchers it works fine.

![new issue](https://user-images.githubusercontent.com/31508893/39871142-47378ace-543a-11e8-8d0c-02e56dd4f26f.png)
![error](https://user-images.githubusercontent.com/31508893/39871143-476e8682-543a-11e8-8edc-2b805add075d.png)

**Comment by piccio** [comment]
solved by [bugfix: enable watchers groups on creating issue](https://github.com/piccio/redmine_watchers_groups/commit/e1994b299eec5e7bc1d9d6ceb8791bb36bcca391)
