### ISSUE TITLE
Support for Ruby < 2.x

### ISSUE THREAD

**Issue by Ernest0x** [piccio/redmine_watchers_groups#2]
It seems that this plugin depends on Ruby >= 2.x. For example, the prepend() method used in init.rb is not available in Ruby 1.9.3. Would you mind supporting older versions of Ruby (1.9.x)?

**Comment by Ernest0x** [comment]
So, @piccio what are your intentions on the above?

**Comment by piccio** [comment]
I'm sorry but, at least for now, I can't support an [obsolete ruby version](https://www.ruby-lang.org/en/news/2015/02/23/support-for-ruby-1-9-3-has-ended/)

**Comment by Ernest0x** [comment]
Ok, fair enough. :)
